// Generated by CoffeeScript 1.4.0
(function() {

  define(["views/entities/Entity", "models/Heightmap"], function(EntityView, heightmapModel) {
    var Creature,
      _this = this;
    return Creature = EntityView.extend({
      tagName: "div",
      className: "creature-tile creature-moving entity-title",
      machineJson: {
        identifier: "idle",
        strategy: "prioritised",
        children: [
          {
            identifier: "move",
            strategy: "sequential",
            children: [
              {
                identifier: "findPath"
              }, {
                identifier: "followPath"
              }, {
                identifier: "idle"
              }
            ]
          }
        ]
      },
      render: function() {
        var _this = this;
        EntityView.prototype.render.call(this);
        this.moveTimer = this.interval(1000 / 2, function() {
          return _this.travel();
        });
        return this;
      },
      interval: function(time, callback) {
        return setInterval(callback, time);
      },
      travel: function() {
        var localArea;
        localArea = heightmapModel.getArea(5, 5, this.model.get("x"), this.model.get("y"));
        if (localArea[2 + 1][2].get("type") === 255) {
          return this.model.set("y", this.model.get("y") + 1);
        } else {
          return clearInterval(this.moveTimer);
        }
      }
    });
  });

}).call(this);
