// Generated by CoffeeScript 1.4.0
(function() {

  define(["views/entities/Entity"], function(EntityView) {
    var Creature;
    return Creature = EntityView.extend({
      tagName: "div",
      className: "creature-tile entity-title",
      render: function() {
        EntityView.prototype.render.call(this);
        return this;
      },
      setStage: function() {
        return this.$el.css({
          backgroundPosition: "-" + (this.model.get("stage") * 16) + "px 0"
        });
      }
    });
  });

}).call(this);
