// Generated by CoffeeScript 1.4.0
(function() {

  define(["models/Viewport", "models/Heightmap", "Backbone"], function(viewportModel, heightmapModel) {
    var Plant;
    return Plant = Backbone.View.extend({
      tagName: "div",
      className: "entity-tile",
      initialize: function() {
        return this.listenTo(viewportModel, "moved", this.onViewportMoved);
      },
      render: function() {
        this.setPosition();
        return this;
      },
      onViewportMoved: function() {
        return this.setPosition();
      },
      setPosition: function() {
        var centerX, centerY, halfWorldHeight, halfWorldWidth, myX, myY, offsetX, offsetY, viewX, viewY, worldHeight, worldWidth, x, y;
        centerX = ~~(viewportModel.get("width") / 2);
        centerY = ~~(viewportModel.get("height") / 2);
        viewX = viewportModel.get("x");
        viewY = viewportModel.get("y");
        myX = this.model.get("x");
        myY = this.model.get("y");
        x = (myX - viewX) + centerX;
        y = (myY - viewY) + centerY;
        worldWidth = heightmapModel.get("worldTileWidth");
        halfWorldWidth = ~~(worldWidth / 2);
        worldHeight = heightmapModel.get("worldTileHeight");
        halfWorldHeight = ~~(worldHeight / 2);
        offsetX = 0;
        offsetY = 0;
        if (myX > viewX + halfWorldWidth) {
          offsetX -= worldWidth;
        }
        if (myX < viewX - halfWorldWidth) {
          offsetX += worldWidth;
        }
        if (myY > viewY + halfWorldHeight) {
          offsetY -= worldHeight;
        }
        if (myY < viewY - halfWorldHeight) {
          offsetY += worldHeight;
        }
        return this.$el.css({
          left: (x + offsetX) * 16,
          top: (y + offsetY) * 16
        });
      }
    });
  });

}).call(this);
