// Generated by CoffeeScript 1.4.0
(function() {

  define(["models/Plant", "Backbone"], function(PlantModel) {
    var Plants;
    Plants = Backbone.Collection.extend({
      model: PlantModel,
      initialize: function() {}
    });
    return new Plants;
  });

}).call(this);
