// Generated by CoffeeScript 1.4.0
(function() {

  define(["models/Heightmap", "models/ViewportTile", "Backbone"], function(heightmap, ViewportTileModel) {
    var ViewportTiles;
    ViewportTiles = Backbone.Collection.extend({
      model: ViewportTileModel,
      initialize: function() {
        var tile, tileRow, tiles, _i, _j, _len, _len1, _ref;
        tiles = [];
        _ref = heightmap.getArea(10, 10, 0, 0);
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          tileRow = _ref[_i];
          for (_j = 0, _len1 = tileRow.length; _j < _len1; _j++) {
            tile = tileRow[_j];
            tiles.push(tile);
          }
        }
        return this.update(tiles);
      }
    });
    return new ViewportTiles;
  });

}).call(this);
