// Generated by CoffeeScript 1.4.0
(function() {

  define(["Backbone"], function() {
    var ViewportTile;
    return ViewportTile = Backbone.View.extend({
      tagName: "div",
      className: "map-tile",
      render: function() {
        return this.setBackgroundPosition();
      },
      setBackgroundPosition: function() {
        var backgroundPositionX, backgroundPositionY;
        backgroundPositionX = 0 - ((this.type % 16) * 16);
        backgroundPositionY = 0 - (~~(this.type / 16) * 16);
        this.$el.css({
          backgroundPosition: "" + backgroundPositionX + "px " + backgroundPositionY + "px"
        });
        return this;
      }
    });
  });

}).call(this);
