// Generated by CoffeeScript 1.4.0
(function() {

  define(["Backbone"], function() {
    var ViewportTile;
    return ViewportTile = Backbone.View.extend({
      tagName: "div",
      className: "map-tile",
      initialize: function() {
        return this.listenTo(this.model, "remove", this.remove);
      },
      render: function() {
        this.$el.css({
          backgroundPositionX: 0 - ((this.model.get("type") % 16) * 16),
          backgroundPositionY: 0 - (~~(this.model.get("type") / 16) * 16)
        });
        return this;
      }
    });
  });

}).call(this);
