// Generated by CoffeeScript 1.4.0
(function() {

  define(["collections/ViewportTiles", "views/viewport/ViewportTile", "models/Viewport", "Backbone"], function(viewportTiles, ViewportTileView, viewportModel) {
    var ViewportView;
    return ViewportView = Backbone.View.extend({
      el: "#tile-viewport",
      initialize: function() {
        var _this = this;
        this.render();
        this.listenTo(viewportModel, "moved", this.render);
        return $(document).keydown(function(jqEvent) {
          var viewportX, viewportY;
          viewportX = viewportModel.get("x");
          viewportY = viewportModel.get("y");
          if (jqEvent.keyCode === 37) {
            viewportX -= 1;
          } else if (jqEvent.keyCode === 38) {
            viewportY -= 1;
          } else if (jqEvent.keyCode === 39) {
            viewportX += 1;
          } else if (jqEvent.keyCode === 40) {
            viewportY += 1;
          }
          return viewportModel.set({
            x: viewportX,
            y: viewportY
          });
        });
      },
      render: function() {
        var _this = this;
        viewportTiles.each(function(viewportTileModel) {
          var viewportTileView;
          viewportTileView = new ViewportTileView({
            model: viewportTileModel
          });
          return _this.$el.append(viewportTileView.render().$el);
        });
        return this;
      }
    });
  });

}).call(this);
