// Generated by CoffeeScript 1.4.0
(function() {

  define(["Backbone"], function() {
    var ViewportTile;
    return ViewportTile = Backbone.View.extend({
      tagName: "div",
      className: "map-tile",
      render: function() {
        var colorBit;
        this.$el.html(this.model.get("data"));
        colorBit = ~~((this.model.get("data") / 10) * 255);
        this.$el.css({
          backgroundColor: "rgb(" + colorBit + ", " + colorBit + ", " + colorBit + ")"
        });
        return this;
      }
    });
  });

}).call(this);
