// Generated by CoffeeScript 1.4.0
(function() {

  define(["views/viewport/Viewport", "Backbone"], function(ViewportView) {
    var AppView;
    return AppView = Backbone.View.extend({
      initialize: function() {
        return new ViewportView;
      }
    });
  });

}).call(this);
