// Generated by CoffeeScript 1.4.0
(function() {

  define(["models/Viewport", "models/Heightmap", "Backbone"], function(viewportModel, heightmapModel) {
    var Plant;
    return Plant = Backbone.View.extend({
      tagName: "div",
      className: "plant-tile",
      initialize: function() {
        return this.listenTo(viewportModel, "moved", this.onViewportMoved);
      },
      render: function() {
        this.setPosition();
        return this;
      },
      onViewportMoved: function() {
        return this.setPosition();
      },
      setPosition: function() {
        var centerX, centerY, viewX, viewY, x, y;
        centerX = ~~(viewportModel.get("width") / 2);
        centerY = ~~(viewportModel.get("height") / 2);
        viewX = viewportModel.get("x");
        viewY = viewportModel.get("y");
        x = (this.model.get("x") - viewX) + centerX;
        y = (this.model.get("y") - viewY) + centerY;
        return this.$el.css({
          left: x * 16,
          top: y * 16
        });
      }
    });
  });

}).call(this);
